plugins {
    id 'scala'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.80'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

file "build.properties" withReader {
    def prop = new Properties()
    prop.load(it)
    ext.config = new ConfigSlurper().parse prop
}

version = "${config.mod.version}"
group = config.mod.group
base.archivesName = config.mod.name

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name "MightyPirates"
        url "https://maven.cil.li/"
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${config.neoforge.version}"
    
    implementation name: 'OC-LuaJ', version: '20220907.1', ext: 'jar'
    implementation name: 'OC-JNLua', version: '20230530.0', ext: 'jar'
    implementation name: 'OC-JNLua-Natives', version: '20220928.1', ext: 'jar'
}

runs {
    client {
        workingDirectory project.file('run')
        
        systemProperty 'neoforge.logging.markers', 'REGISTRIES'
        systemProperty 'neoforge.logging.console.level', 'debug'
        
        mods {
            opencomputers {
                source sourceSets.main
            }
        }
    }
    
    server {
        workingDirectory project.file('run')
        
        systemProperty 'neoforge.logging.markers', 'REGISTRIES'
        systemProperty 'neoforge.logging.console.level', 'debug'
        
        mods {
            opencomputers {
                source sourceSets.main
            }
        }
    }
}

mappings channel: "${config.minecraft.mappings_channel}", version: "${config.minecraft.mappings_version}"

jar {
    from(configurations.runtimeClasspath.findAll { it.name.startsWith('OC-') }.collect { zipTree(it) }) {
        exclude 'META-INF', 'META-INF/**'
    }
    
    manifest {
        attributes([
            "Specification-Title": "OpenComputers",
            "Specification-Vendor": "MightyPirates",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": project.version,
            "Implementation-Vendor": "MightyPirates"
        ])
    }
}

processResources {
    inputs.property "version", "${config.mod.version}"
    inputs.property "mcversion", config.minecraft.version
    inputs.property "neoforge_version", config.neoforge.version
    
    filesMatching(['META-INF/mods.toml']) {
        expand 'version': "${config.mod.version}", 
               'mcversion': config.minecraft.version, 
               'neoforge_version': config.neoforge.version
    }
}