pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name 'NeoForged'
            url 'https://maven.neoforged.net/releases'
        }
        maven {
            name 'MinecraftForge'
            url 'https://files.minecraftforge.net/maven'
        }
        maven {
            name 'FancyGradle'
            url 'https://maven.gofancy.wtf/releases'
        }
    }
}
rootProject.name = "opencomputers-1.20.1-neoforge"
